//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CEN_PRODUCTS
    {
        public int PRODUCT_SK { get; set; }
        public int MEDIA_TYPE_SK { get; set; }
        public decimal PRODUCT_ID { get; set; }
        public string ISBN_13 { get; set; }
        public string ISBN_10 { get; set; }
        public string TITLE { get; set; }
        public Nullable<decimal> EDITION { get; set; }
        public string COPYRIGHT_YEAR { get; set; }
        public string PUB_STATUS_CODE { get; set; }
        public Nullable<System.DateTime> PUBLICATION_DATE { get; set; }
        public string SUBJECT_KEYWORDS { get; set; }
        public string BLOCK_FLAG { get; set; }
        public string PACK_TYPE { get; set; }
        public string PROMOTION_READY_FLAG { get; set; }
        public string INTERNAL_PROMOTION_FLAG { get; set; }
        public string ARCHIVED_FLAG { get; set; }
        public Nullable<int> NO_OF_PAGES { get; set; }
        public string ON_APPROVAL_FLAG { get; set; }
        public Nullable<decimal> YTD { get; set; }
        public string TOC { get; set; }
        public string FEATURES { get; set; }
        public string DESCRIPTION { get; set; }
        public string STOCK_STATUS { get; set; }
        public Nullable<decimal> STOCK_QUANTITY { get; set; }
        public string EPUB_FILE_LOCATION { get; set; }
        public string ACTIVE { get; set; }
        public string STATUS { get; set; }
        public System.DateTime DATE_CREATED { get; set; }
        public string USER_CREATED { get; set; }
        public Nullable<System.DateTime> DATE_MODIFIED { get; set; }
        public string USER_MODIFIED { get; set; }
        public string AUDIENCE_CODE { get; set; }
        public string IMPRINT { get; set; }
        public string SAMPLING_RESTRICTION_CODE { get; set; }
        public string PERMANANT_ACTIVE { get; set; }
        public string PUBLISHED_BY { get; set; }
        public string LOCAL_IMPORT { get; set; }
        public string COUNTRY { get; set; }
        public string PUBLISHER_CODE { get; set; }
        public string COUNTRY_OF_ORIGIN { get; set; }
        public string PRODUCT_TYPE { get; set; }
        public string PRODUCT_FORMAT { get; set; }
        public string PRODUCT_FORMAT_TYPE { get; set; }
        public string TLID { get; set; }
        public string eBook_Platform_Name { get; set; }
        public string BINDING_FORMAT { get; set; }
        public string DDC { get; set; }
        public Nullable<decimal> NUMBER_OF_VOLUMES { get; set; }
        public string PROMOTION_CODE { get; set; }
        public Nullable<int> SUBSTITUTE_PRODUCT_SK { get; set; }
        public string SUBSTITUTE_ISBN13 { get; set; }
        public string PROD_TITLE { get; set; }
    }
}
