//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ECOMM_S3Entities : DbContext
    {
        public ECOMM_S3Entities()
            : base("name=ECOMM_S3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CEN_PRODUCTS> CEN_PRODUCTS { get; set; }
        public virtual DbSet<temp_customers> temp_customers { get; set; }
    
        public virtual ObjectResult<sp_getproducts_Result> sp_getproducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getproducts_Result>("sp_getproducts");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_registerUser(string userName, string password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));

            //var OutPutParameter = new ObjectParameter("@new_identity", typeof(string));
            //OutPutParameter.Direction = ParameterDirection.Output;
            //SqlCommand.Parameters.Add(OutPutParameter);

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_registerUser", userNameParameter, passwordParameter);
        }
    }
}
